import { ThemeProvider } from "styled-components";
import GlobalStyles from "../src/styles/GlobalStyles";
import theme from "../src/styles/theme";
import "../src/i18n"; 
import Head from "next/head";
import NavBar from "../src/components/NavBar/NavBar";
import Footer from "../src/components/Footer/Footer";

export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      {/* Opcional: Añadir metadatos globales en todas las páginas */}
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Component {...pageProps} />
      <Footer/>
    </ThemeProvider>
  );
}

// import React, { Suspense, lazy, useRef, useState, useEffect } from "react";
// import { BrowserRouter as Router } from "react-router-dom";
// import NavBar from "./components/NavBar/NavBar";
// import GlobalStyles from "./styles/GlobalStyles";
// import AnimatedElement from "./components/AnimatedElement/AnimatedElement";
// import Footer from "./components/Footer/Footer";
// import Spinner from "./components/Spinner/Spinner";
// import ScrollToTopButton from "./components/Button/ScrollToTopButton";
// import useIsDesktop from "./Hooks/useIsDesktop";

// const HomePage = lazy(() => import("./pages/HomePage/HomePage"));
// const ContactUs = lazy(() => import("./pages/ContactUs/ContactUs"));
// const Services = lazy(() => import("./pages/Services/Services"));
// const AboutUs = lazy(() => import("./pages/AboutUs/AboutUs"));

// function App() {
//   const [isRestLoaded, setIsRestLoaded] = useState(false);
//   const isDesktop = useIsDesktop();
//   useEffect(() => {
//     const timer = setTimeout(() => {
//       setIsRestLoaded(true);
//     }, 1000);

//     return () => clearTimeout(timer);
//   }, []);

//   const homeRef = useRef(null);
//   const aboutUsRef = useRef(null);
//   const servicesRef = useRef(null);
//   const contactUsRef = useRef(null);

//   return (
//     <Router>
//       <GlobalStyles />
//       <NavBar
//         homeRef={homeRef}
//         aboutUsRef={aboutUsRef}
//         servicesRef={servicesRef}
//         contactUsRef={contactUsRef}
//       />
//       <div>
//         <AnimatedElement threshold={0.5}>
//           <HomePage ref={homeRef} />
//         </AnimatedElement>
//         {isRestLoaded && (
//           <Suspense fallback={<Spinner />}>
//             {isDesktop ? (
//               <AnimatedElement threshold={0.1}>
//                 <Services ref={servicesRef} />
//               </AnimatedElement>
//             ) : (
//               <AnimatedElement threshold={0.01}>
//                 <Services ref={servicesRef} />
//               </AnimatedElement>
//             )}
//             {isDesktop ? (
//               <AnimatedElement threshold={0.1}>
//                 <AboutUs ref={aboutUsRef} />
//               </AnimatedElement>
//             ) : (
//               <AnimatedElement threshold={0.001}>
//                 <AboutUs ref={aboutUsRef} />
//               </AnimatedElement>            )}
//             <AnimatedElement threshold={0.5}>
//               <ContactUs ref={contactUsRef} />
//             </AnimatedElement>
//           </Suspense>
//         )}
//       </div>

//       <ScrollToTopButton />
//       <Footer />
//     </Router>
//   );
// }

// export default App;
