import { ThemeProvider } from "styled-components";
import GlobalStyles from "../src/styles/GlobalStyles";
import theme from "../src/styles/theme";
import "../src/i18n";
import Head from "next/head";
import NavBar from "../src/components/NavBar/NavBar";
import Footer from "../src/components/Footer/Footer";
import styled from "styled-components";

const Layout = styled.div`
  display: flex;
  flex-direction: column;
  min-height: 100vh; 
`;

const Main = styled.main`
  flex: 1; 
`;

export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <Head>
        <title>OpenGateHub</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <NavBar />
        <Main>
          <Component {...pageProps} />
        </Main>
        <Footer />
      </Layout>
    </ThemeProvider>
  );
}
